# Site settings
title: BryanWP 
email: bwp.pearson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Full-stack systems engineer at ReverbNation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  bryanwp

# Build settings
markdown: kramdown
